allowBuilds:
  better-sqlite3: true
  esbuild: true
  lefthook: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - '@trickfilm400/rollup-plugin-off-main-thread@3.0.0-pre1'
trustPolicyIgnoreAfter: 525600
shellEmulator: true
