/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>;

export interface GoalLogs {
	date: string;
	goalId: number;
	id: Generated<number | null>;
	orderNumber: number | null;
	type: string;
}

export interface Goals {
	active: number;
	color: string;
	description: string | null;
	id: Generated<number | null>;
	orderNumber: number;
	title: string;
}

export interface Intentions {
	date: string;
	goalId: number;
	id: Generated<number | null>;
	orderNumber: number;
	status: 'pending' | 'done' | 'not_today';
	subIntentionQualifier: string | null;
	text: string;
}

export interface Outcomes {
	date: string;
	id: Generated<number | null>;
	reviewed: number;
}

export interface OutcomesIntentions {
	intentionId: number;
	outcomeId: number;
}

export interface OutcomeVerdicts {
	goalId: number;
	id: Generated<number | null>;
	note: string | null;
	outcomeId: number;
	verdict: 'enough' | 'not_enough' | 'day_off';
}

export interface Priorities {
	checkInDate: string | null;
	completedAt: string | null;
	createdAt: string;
	description: string | null;
	goalId: number;
	id: Generated<number | null>;
	reflection: string | null;
	text: string;
}

export interface Settings {
	key: string;
	value: string;
}

export interface DB {
	goal_logs: GoalLogs;
	goals: Goals;
	intentions: Intentions;
	outcome_verdicts: OutcomeVerdicts;
	outcomes: Outcomes;
	outcomes_intentions: OutcomesIntentions;
	priorities: Priorities;
	settings: Settings;
}
