/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>;

export interface GoalLogs {
	date: string;
	goalId: number;
	id: Generated<number | null>;
	orderNumber: number | null;
	type: string;
}

export interface Goals {
	active: number;
	color: string;
	description: string | null;
	id: Generated<number | null>;
	orderNumber: number;
	title: string;
}

export interface Intentions {
	completed: number;
	date: string;
	goalId: number;
	id: Generated<number | null>;
	orderNumber: number;
	subIntentionQualifier: string | null;
	text: string;
}

export interface Outcomes {
	date: string;
	id: Generated<number | null>;
	reviewed: number;
}

export interface OutcomesIntentions {
	intentionId: number;
	outcomeId: number;
}

export interface DB {
	goal_logs: GoalLogs;
	goals: Goals;
	intentions: Intentions;
	outcomes: Outcomes;
	outcomes_intentions: OutcomesIntentions;
}
